// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpIuRCiGVJY4WvCHm1Mln7VJEyw8gokQ',
    appId: '1:729304122110:web:5816192c2b863098469baf',
    messagingSenderId: '729304122110',
    projectId: 'mozilit',
    authDomain: 'mozilit.firebaseapp.com',
    storageBucket: 'mozilit.appspot.com',
    measurementId: 'G-MW29QM777F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUTQbTzw8b7bkiywpM7oayMl2ugpzReUU',
    appId: '1:729304122110:android:f86b6b19afa66810469baf',
    messagingSenderId: '729304122110',
    projectId: 'mozilit',
    storageBucket: 'mozilit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRHwVYz1gRrRk9-O124YIcD9cg71yuEfI',
    appId: '1:729304122110:ios:c4cfd1a115cc3592469baf',
    messagingSenderId: '729304122110',
    projectId: 'mozilit',
    storageBucket: 'mozilit.appspot.com',
    iosClientId: '729304122110-2skg505m8mtjp1d3g2j50c37ubdl8ek3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mozilit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRHwVYz1gRrRk9-O124YIcD9cg71yuEfI',
    appId: '1:729304122110:ios:02c4b920102c6578469baf',
    messagingSenderId: '729304122110',
    projectId: 'mozilit',
    storageBucket: 'mozilit.appspot.com',
    iosClientId: '729304122110-5n0g2934i7v6grlp2t2mnhl51oc810mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mozilit.RunnerTests',
  );
}
